spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ad-campaign
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    ddl-auto: update

server:
  port: 8443
  ssl:
    key-store:
    key-store-password: changeit
    key-password: changeit